# Generated by Django 2.2.7 on 2020-02-11 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervalo', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitante', models.CharField(max_length=120)),
                ('observacoes', models.CharField(blank=True, max_length=150, null=True)),
                ('aulas', models.ManyToManyField(to='agenda.Horarios')),
                ('dias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.Dia')),
                ('local_solicitado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.Local')),
            ],
        ),
    ]
