# Generated by Django 2.2.7 on 2019-11-27 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fim_uso', models.TimeField()),
                ('inicio_uso', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.CharField(max_length=120)),
                ('laboratorio', models.CharField(choices=[('1', 'Laboratório de Redes de Computadores'), ('2', 'Laboratório de Informática'), ('3', 'Laboratório de Arquitetura de Computadores')], max_length=1)),
                ('professor', models.CharField(max_length=120)),
                ('soft_uso', models.CharField(blank=True, max_length=120, null=True)),
                ('turno', models.CharField(choices=[('1', 'Manhã'), ('2', 'Tarde'), ('3', 'Noite')], max_length=1)),
                ('dia_semana', models.CharField(choices=[('1', 'Segunda-Feira'), ('2', 'Terça-Feira'), ('3', 'Quarta-Feira'), ('4', 'Quinta-Feira'), ('5', 'Sexta-Feira')], max_length=1)),
                ('horario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='agenda.Horario')),
            ],
        ),
    ]
