# Generated by Django 2.2.7 on 2019-12-09 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vagas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laboratorio', models.CharField(max_length=120)),
                ('turno', models.CharField(max_length=120)),
                ('intervalo', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('1', 'Livre'), ('2', 'Ocupado')], max_length=1)),
            ],
        ),
    ]
